### ISSUE TITLE
Path specific middleware fails to split traffic

### ISSUE THREAD

**Issue by curiousercreative** [aiji42/next-with-split#140]
1. Visit path (/foo/bar) with traffic splitting enabled and receive the challenger/variation (verify presence of cookie)
2. Navigate to web root (/) and reload.
3. Navigate to path from step1 (using Next links, SPA navigations)
ER: experience should match step1 variation experience
AR: experience is control
4. Reload the window
ER/AR: experience matches step1 variation experience

**Comment by aiji42** [comment]
Thanks for reporting the problem.
I have investigated the issue and found out that it is a bug in the navigation behavior with preflight. I am working on a fix now.

**Comment by aiji42** [comment]
I have released v4.2.1, which addresses this issue. Please update to the latest version and give it a try.
