### ISSUE TITLE
Unable to navigate by prefetch on A/B test target paths

### ISSUE THREAD

**Issue by aiji42** [aiji42/next-with-split#143]
#141 This release disabled navigation by prefetch for visitors allocated to the challenger, and caused a full page load.

## Solutions
- Preflight from outside the target path of A/B tests will not be given `x-middleware-rewrite`.
    - Do not allow prefetch to be used.
- Preflight from inside the target path of A/B tests will be given `x-middleware-rewrite`.
    - Prefer prefetch navigation.

**Comment by curiousercreative** [comment]
@aiji42 good news and bad news :) The navigation and cookie setting is working nicely. Unfortunately, we're back to the experience not matching the cookie.
1. Start on a path that is not split
    ER/AR: no cookie is set
2. Navigate in-app to the path that is split
    ER/AR: cookie is set
    ER: experience matches cookie
    AR: experience is always control
3. Refresh the page
    ER/AR: experience matches cookie

**Comment by aiji42** [comment]
@curiousercreative Thanks. Although the event is a little different, I'm also experiencing an issue where I'm not getting assigned to Challenger when navigating from non-target, but 100% assigned to Original, which I'm currently investigating.

**Comment by aiji42** [comment]
@curiousercreative I have published 4.2.3-beta.1 which resolves the above issue. I would like to ask you to confirm whether the problem you reported is resolved in 4.2.3-beta.1 or not. If the problems are resolved, I will release it as 4.2.3.

**Comment by curiousercreative** [comment]
@aiji42 with a quick test of 4.2.3-beta.1, I see experience matches cookie, however I also see that any path that is subject to traffic splitting is back to full document request, hard navigation.

**Comment by aiji42** [comment]
@curiousercreative What configuration of the pages are you experiencing the problem with? I don't seem to have that problem with my [sample site](https://next-with-split.vercel.app/top).

Out of range: /top
In scope: /foo/bar, /foo/baz
- When assigned to the original
    - /top -> /foo/bar : Navigating by partial loading with prefetch.
    - /foo/bar/ -> /foo/baz : Navigating by partial loading with prefetch.
- When assigned to the challenger
    - /top -> /foo/bar : Navigating by full page load.
    - /foo/bar/ -> /foo/baz : Navigating by partial loading with prefetch.

**Comment by curiousercreative** [comment]
@aiji42 I apologize, I should have specified that I was looking at challenger allocation. What you described matches my experience and I'd hope we can have both challenger and original "navigating by partial loading with prefetch".

**Comment by aiji42** [comment]
> I'd hope we can have both challenger and original "navigating by partial loading with prefetch".

That's right. Of course, I would like to do so if it were possible, but this is not feasible at this time due to Next.js specifications.

The manifest file (resource mapping definition file) for Prefetch is delivered to the browser when the page is accessed. In other words, when you land on a site for the first time, the resources that can be prefetched have already been determined. Therefore, the Challenger resource cannot be prefetched from a page outside the scope of the A/B test, and if it is assigned to the Challenger, it dares to navigate with a full page load to load the manifest file for the Challenger into the browser.

There seems to be no problem with 4.2.3-beta.1, so I would like to release it as 4.2.3.
