### ISSUE TITLE
Edge browser (MacOS): Cookie switches to 'original' after showing the challenger page

### ISSUE THREAD

**Issue by mhoev** [aiji42/next-with-split#81]
Hi,

Thanks for this great project! I started testing today and the split testing works like a charm.

Unfortunately, when using MS Edge (at least on Mac), the behaviour is other than expected: Every time the challenger page is shown, the content of the x-split-key-example1 cookie is first set to 'test' but switches to 'original' c. 500ms later. Consequently, after a reload or revisit of the page,  it is always the original version that is displayed.

Safari and Chrome on macOS both work fine.

Deployment is to Vercel with standard settings.

Any idea? Happy to provide more information if this may help. 

Many thanks,
Markus

**Comment by aiji42** [comment]
Hi Markus,
Thank you for reporting a valuable issue.

I have never seen it work in Edge. This plugin may not work properly in certain browsers because different browsers handle cookies differently.
If I can see a similar problem at hand, I will improve it.

Thank you!

**Comment by aiji42** [comment]
I have verified this using Edge for Mac and have not seen the problem reported.
It seems that the cookies are not reset in the same way as Chrome and Safari, and once split, they reach the same distribution when re-accessed.

Is this configuration the same as #82? If so, please try again, specifying the path to test instead of all paths.

**Comment by aiji42** [comment]
This URL is an example of a simple split test.

https://next-with-split.vercel.app/foo/bar/hoge 
original: black
challenger: red

Please let me know how it behaves when you access this from your Edge.

**Comment by aiji42** [comment]
That was good!
I will update the Readme based on your Issue.
